# Generated by Django 5.1.3 on 2025-03-04 09:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spravki', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='Справки')),
                ('postcpgu', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='ПОСТ  ЦПГУ')),
                ('trebmil', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='ТРЕБ МИЛ')),
                ('vlkart', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='ВЛИТИЯ КАРТ')),
                ('aktual', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='АКТУАЛ')),
                ('akt_sud', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='АКТ СУД РЕЕСТ')),
                ('postprekr', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='ПОСТ ПРЕКР')),
                ('postad', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='ПОСТ ОБЬЯВЛ')),
                ('istreb', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)], verbose_name='ИСТРЕБОВАНИЕ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
