# Generated by Django 5.1.3 on 2025-01-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akt_sud',
            name='value',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True, verbose_name='АКТ СУД РЕЕСТ'),
        ),
        migrations.AlterField(
            model_name='aktual',
            name='value',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True, verbose_name='АКТУАЛ'),
        ),
        migrations.AlterField(
            model_name='istreb',
            name='value',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True, verbose_name='ИСТРЕБОВАНИЕ'),
        ),
        migrations.AlterField(
            model_name='post_ad',
            name='value',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True, verbose_name='ПОСТ ОБЬЯВЛ'),
        ),
        migrations.AlterField(
            model_name='post_prеkr',
            name='value',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True, verbose_name='ПОСТ ПРЕКР'),
        ),
        migrations.AlterField(
            model_name='postcpgu',
            name='value',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True, verbose_name='ПОСТ  ЦПГУ'),
        ),
        migrations.AlterField(
            model_name='spravki',
            name='value',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True, verbose_name='Справки'),
        ),
        migrations.AlterField(
            model_name='trebmil',
            name='value',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True, verbose_name='ТРЕБ МИЛ'),
        ),
        migrations.AlterField(
            model_name='vlkart',
            name='value',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True, verbose_name='ВЛИТИЯ КАРТ'),
        ),
    ]
